name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Stok awal 10
      id: stok-awal-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Stok awal 10
        setup-command: javac TugasPerulangan.java
        command: java TugasPerulangan
        input: |-
          10
          2
        expected-output: "-1"
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Stok awal 100 kurang 3
      id: stok-awal-100-kurang-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Stok awal 100 kurang 3
        setup-command: javac TugasPerulangan.java
        command: java TugasPerulangan
        input: |-
          100
          3
        expected-output: '16'
        comparison-method: regex
        timeout: 10
        max-score: 20
    - name: Stok awal 100 kurang 4
      id: stok-awal-100-kurang-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Stok awal 100 kurang 4
        setup-command: javac TugasPerulangan.java
        command: java TugasPerulangan
        input: |-
          100
          4
        expected-output: "-1"
        comparison-method: exact
        timeout: 10
        max-score: 20
    - name: Deret 3
      id: deret-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Deret 3
        setup-command: javac TugasPerulangan2.java
        command: java TugasPerulangan2
        input: '5'
        expected-output: |-
          3
          6
          9
          12
          15
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Max 10
      id: max-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Max 10
        setup-command: javac TugasPerulangan2.java
        command: java TugasPerulangan2
        input: '7'
        expected-output: |-
          3
          6
          9
          12
          15
          18
          21
        comparison-method: exact
        timeout: 10
        max-score: 20
    - name: Maksimal 10
      id: maksimal-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Maksimal 10
        setup-command: javac TugasPerulangan2.java
        command: java TugasPerulangan2
        input: '10'
        expected-output: |-
          3
          6
          9
          12
          15
          18
          21
          24
          27
          30
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        STOK-AWAL-10_RESULTS: "${{steps.stok-awal-10.outputs.result}}"
        STOK-AWAL-100-KURANG-3_RESULTS: "${{steps.stok-awal-100-kurang-3.outputs.result}}"
        STOK-AWAL-100-KURANG-4_RESULTS: "${{steps.stok-awal-100-kurang-4.outputs.result}}"
        DERET-3_RESULTS: "${{steps.deret-3.outputs.result}}"
        MAX-10_RESULTS: "${{steps.max-10.outputs.result}}"
        MAKSIMAL-10_RESULTS: "${{steps.maksimal-10.outputs.result}}"
      with:
        runners: stok-awal-10,stok-awal-100-kurang-3,stok-awal-100-kurang-4,deret-3,max-10,maksimal-10
